# Generated by Django 3.2.9 on 2021-12-26 16:56

from django.db import migrations, models
import django.db.models.deletion
import enrollment_data_show.models
import private_storage.fields
import private_storage.storage.files


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CourseInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('courses', models.CharField(max_length=200)),
                ('creditHours', models.CharField(max_length=100)),
                ('creditPassed', models.FloatField(default=10)),
                ('grades', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=100)),
                ('accessible_fields', models.CharField(max_length=200)),
                ('key', models.CharField(max_length=16)),
            ],
        ),
        migrations.CreateModel(
            name='EconomicInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nid_number', models.IntegerField(null=True)),
                ('student_occupation', models.CharField(max_length=50, null=True)),
                ('student_annual_income', models.FloatField(null=True)),
                ('bank_account_number', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PersonalInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_birth', models.DateField(null=True)),
                ('gender', models.CharField(max_length=6, null=True)),
                ('bloodGroup', models.CharField(max_length=3, null=True)),
                ('marital_status', models.CharField(max_length=10, null=True)),
                ('phone_number', models.CharField(max_length=14, null=True)),
                ('fathers_name', models.CharField(max_length=100, null=True)),
                ('fathers_occupation', models.CharField(max_length=50, null=True)),
                ('fathers_phone_number', models.CharField(max_length=14, null=True)),
                ('mothers_name', models.CharField(max_length=100, null=True)),
                ('mothers_occupation', models.CharField(max_length=50, null=True)),
                ('mothers_phone_number', models.CharField(max_length=14, null=True)),
                ('address', models.CharField(max_length=250, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('image', private_storage.fields.PrivateFileField(storage=private_storage.storage.files.PrivateFileSystemStorage(), upload_to=enrollment_data_show.models.image_dir)),
                ('nsuID', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('birth_certificate_number', models.IntegerField()),
                ('department', models.CharField(max_length=100)),
                ('majorIn', models.CharField(max_length=100)),
                ('enrolled_in', models.IntegerField()),
                ('cgpa', models.FloatField()),
                ('sscPassYear', models.IntegerField()),
                ('sscGpa', models.FloatField()),
                ('hscPassYear', models.IntegerField()),
                ('hscGpa', models.FloatField()),
                ('course_info', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='student_course_info', to='enrollment_data_show.courseinfo')),
                ('economic_info', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='student_economic_info', to='enrollment_data_show.economicinfo')),
                ('personal_info', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='student_personal_info', to='enrollment_data_show.personalinfo')),
            ],
        ),
    ]
